### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#253]
There are not enough unit tests in knora-app. 

We have to add unit tests to the following components (there is a todo list in each spec file):

+ main/
  - [x] main -> FL - part of #256 
  - [ ] cache.service
  - [x] cookie-policy -> FL part of #256 
  - [ ] error -> e2e
  - [x] footer -> e2e FL - part of #256 
  - [x] header -> FL - part of #256 
  - [x] help -> e2e
  - [x] login -> FL - part of #256 
+ project/
  - [ ] project
  - [ ] board -> FL WIP
  - [ ] collaboration
  - [ ] project-form
  -> list should be done with the refactoring
+ system/
  - [ ] projects
  - [ ] users
  - [ ] system
+ user/
  - [ ] user
  - [ ] account
  - [ ] dashboard
  - [ ] membership
  - [ ] profile
  - [ ] user-form
  - [ ] user-menu
+ workspace/
  -> unit tests done in the modules, could add here some unit tests to test something specific to the knora-app UI

**Comment by flavens** [comment]
@kilchenmann could you check the `error` and `footer` components to see what could be tested? And in main component, I added some tests but maybe we need more.

**Comment by flavens** [comment]
the unit tests in DSP-APP must be refactored to use the mock factory of DSP-JS-LIB
this will be a continuous process
